apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cluster-secret: |-
    ODUwZDc3ZWMxMDY5M2I3ZDdiZDIxMDI3ZWJkYTNhMDE3YzZhZjVhYzhjYjFiOGY3OWI2ZDAwZjk1ZTc1MjhmMQ==
